server:
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  banner:
    location: classpath:static/banner.txt
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true